### ISSUE TITLE
MacBook Pro (Retina, 15-inch, Late 2013)

### ISSUE THREAD

**Issue by joker5bb** [stefanpartheym/mbp15-wifi-driver#1]
I have the 
03:00.0 Network controller [0280]: Broadcom Inc. and subsidiaries BCM4360 802.11ac Wireless Network Adapter [14e4:43a0] (rev 03)

How can I extract the firmware for this chipset?

**Comment by stefanpartheym** [comment]
I can't say for sure, however you might have success trying the `collect.sh` script from this repository.
You would have to change line 22 like this:
```
version="4360"
```
and then run the script on your MacOS.

If you try this, please give me feedback, I'm curious if it works ;)

**Comment by stefanpartheym** [comment]
Closing this issue as there was no feedback.
