### ISSUE TITLE
Not able to connect to password protected Wifi’s (Can’t Authenticate)

### ISSUE THREAD

**Issue by tanner02** [stefanpartheym/mbp15-wifi-driver#3]
Hi !
Thanks for the script. My WiFi works now, however, I can’t connect to password protected WiFi’s.
After entering the password it’s showing “Connecting...” but prompts me to re-enter the password again after a couple seconds.

Edit: It’s a MacBook15,2 running Linux Mint (Kernel 5.7.1)
Edit2: Was also happening on Manjaro

**Comment by stefanpartheym** [comment]
Hmm, this is very strange. I use the same MBP model. However I use Archlinux (Kernel **5.6.18**). Maybe something changed regarding the wifi in version 5.7.1. I can't tell.
Also make sure your MacOS wasn't already on Catalina. I think a few people had problems with that version of MacOS.
If in doubt, just use the driver files already in the `driver-files` directory of this repository. They are from my MBP (Mojave).
You could also clone the repository and execute the `collect.sh` script and then run a `git status` or `git diff` to check if something changed (i.e. different versions of the driver files).

**Comment by aunali1** [comment]
@stefanpartheym I might be worthwhile to just pull the files from my complete Mojave archive at https://packages.aunali1.com/apple/wifi-fw.

**Comment by stefanpartheym** [comment]
Hey @aunali1 , sure. That is what the `download.sh` script is for 😉
Also thank you for hosting that and the patched linux kernels 🙏

**Comment by tanner02** [comment]
Thanks for your reply !
I tried the provided driver-files now, still the same problem though :/
Yes im running Mojave (10.14.6). I also just tried using the same kernel version as yours (5.6.18), and now even Wifi doesn't work. _bummer_
Before trying Linux Mint, I was trying Manjaro (Kernel 5.7.17) with **aunali1's** Kernel Patches for Arch and **MCMrARM's** BCE Drivers. It practically didn't change anything. Touchpad, Keyboard, Wifi etc. still didn't work. At least Wifi was working after using your Script, but like right now, it was working partially as I can't connect to secured networks.

**Comment by stefanpartheym** [comment]
Make sure you are using `iwd` to connect to wifis. If you are using NetworkManager you can configure it to use `iwd` as backend in `/etc/NetworkManager/NetworkManager.conf`:
```
# ...
[device]
wifi.backend=iwd
```

**Comment by tanner02** [comment]
Configuring NetworkManager to use `iwd` as backend made WiFi “Unavailable”.
I guess I’ll just abandon this for now as nothing seems to work :/

Edit: Reading the wpa_supplicant log I found `nl80211: Driver does not support authentication/association or connect commands`
Might not help much but it’s at least something :)

**Comment by stefanpartheym** [comment]
Hmm very strange. I might already said everything, but maybe there is some information for you in this one: https://gist.github.com/TRPB/437f663b545d23cc8a2073253c774be3#wifi

Much luck!

**Comment by tanner02** [comment]
I found a similar one earlier this day (actually the same but with [Manjaro](https://github.com/JPyke3/mbp-manjaro)) I used the precompiled ISO (contains Aunali1's Kernel Patch and BCE Driver and MCMrARM's Bridge Driver) and installed it alongside Mint. It was a relief to finally see a working Keyboard, Touchpad and Sound. Wifi wasn't working out of the Box but was quickly fixed by putting the driver files into the desired folder. Unfortunately ... I still have the problem not being able to connect to secured networks :/

But thanks !
You or i can close the Issue if you think that you can't help me any further 😅
And thanks for trying to help !

Small Edit: ioreg says Firmware"="C-4364__s-B2/maui.trx but when I check that file its just a 0 byte file and is linked "Show Original" to ekans.trx. I feel like that's not normal so I wanted to ask :)

**Comment by stefanpartheym** [comment]
Hmm damn...
Unfortunately this mbp model is not yet perfectly supported. We can just hope that great people like @aunali1 or @MCMrARM and others will have the time to bring things further.
I'm using Archlinux on my mbp for 4 month now. At home, at work. Not everything works but I still like it more than my MacOS :D
However I use external mouse, keyboard and monitor.

I will close the issue now.

**Comment by tanner02** [comment]
Very sorry ~~for reopening the issue~~ but I wanted to make sure if you saw the edit on my previous comment:

> Small Edit: ioreg says Firmware"="C-4364__s-B2/maui.trx but when I check that file its just a 0 byte file and is linked "Show Original" to ekans.trx. I feel like that's not normal so I wanted to ask :)

**Comment by stefanpartheym** [comment]
Oh you're welcome.
Hmm strange very strange. In this case I recommend using the driver files from this repository. Or as @aunali1 said, from his archive (see `download.sh`). ;)

**Comment by tanner02** [comment]
Oh uh, alright then :D
Thanks !

**Comment by venkcy** [comment]
Hi @stefanpartheym
My 2020 Mac mini has the same issue with Clear Linux.
 I am able to connect to open network but 2.4ghz secured keeps prompting for password and 5ghz doesn’t prompt for password but the status icon keeps revolving.
