### ISSUE TITLE
Using in mbp-manjaro

### ISSUE THREAD

**Issue by JPyke3** [stefanpartheym/mbp15-wifi-driver#4]
Servus,

After having a look over your scripts. Would you mind if I add your repository to the readme of https://github.com/JPyke3/mbp-manjaro?

I am trying to make the install procedure for Manjaro as streamlined as possible to reflect how the distribution acts on mainline kernels.

As such I would really appreciate if I could just add a link to your repo in the install procedure and to follow your instructions to recieve the WiFi firmware files from MacOS and transplant them into linux.

Didn't want to do it without your permission though :)

**Comment by stefanpartheym** [comment]
Servus @JPyke3 :)

sorry, this might be a bit late (roughly 2 years). Of course you can use/mention this repo where every and however you want ;)

Best regards
Stefan
